"""Generate the Supabase stages/concepts seed migration from stages.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def generate(source: Path) -> str:
    payload = json.loads(source.read_text(encoding="utf-8"))
    lines = [
        "-- Generated by scripts/generate_stage_seed_sql.py; do not edit by hand.",
        "-- Source: data/stages.json",
        "",
        "begin;",
        "",
    ]
    for fallback_order, stage in enumerate(payload["stages"], start=1):
        stage_id = str(stage["id"])
        order = int(stage.get("order", fallback_order))
        optional = "true" if bool(stage.get("is_optional", False)) else "false"
        lines.extend(
            [
                "insert into public.stages (stage_id, name_ko, display_order, is_optional)",
                f"values ({_literal(stage_id)}, {_literal(str(stage['name_ko']))}, {order}, {optional})",
                "on conflict (stage_id) do update set",
                "  name_ko = excluded.name_ko,",
                "  display_order = excluded.display_order,",
                "  is_optional = excluded.is_optional;",
                "",
            ]
        )
        for fallback_concept_order, concept in enumerate(stage["concepts"], start=1):
            concept_order = int(concept.get("order", fallback_concept_order))
            lines.extend(
                [
                    "insert into public.concepts (concept_id, stage_id, term, display_order)",
                    f"values ({_literal(str(concept['concept_id']))}, {_literal(stage_id)}, "
                    f"{_literal(str(concept['term']))}, {concept_order})",
                    "on conflict (concept_id, stage_id) do update set",
                    "  term = excluded.term,",
                    "  display_order = excluded.display_order;",
                    "",
                ]
            )
    lines.extend(["commit;", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("data/stages.json"))
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("migrations/003_seed_stages_concepts.sql"),
    )
    args = parser.parse_args()
    args.output.write_text(generate(args.source), encoding="utf-8", newline="\n")
    print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
