-- Generated by scripts/generate_stage_seed_sql.py; do not edit by hand.
-- Source: data/stages.json

begin;

insert into public.stages (stage_id, name_ko, display_order, is_optional)
values ('stage1', '사회경제현상과 소비생활', 1, false)
on conflict (stage_id) do update set
  name_ko = excluded.name_ko,
  display_order = excluded.display_order,
  is_optional = excluded.is_optional;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1281', 'stage1', '분업/특화', 1)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1963', 'stage1', '워킹푸어', 2)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_980', 'stage1', '렌트 푸어', 3)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1123', 'stage1', '민달팽이세대', 4)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_15', 'stage1', '88만원세대', 5)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_842', 'stage1', '니트족', 6)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2375', 'stage1', '중규직', 7)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2011', 'stage1', '유리천장', 8)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1704', 'stage1', '실업수당 청구건수', 9)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_419', 'stage1', '고령화사회', 10)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2173', 'stage1', '장수리스크', 11)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1498', 'stage1', '소득 크레바스', 12)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1', 'stage1', '0.5인 가구', 13)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2309', 'stage1', '젠트리피케이션', 14)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1047', 'stage1', '메가시티', 15)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1382', 'stage1', '산업공동화', 16)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_923', 'stage1', '도시형주택', 17)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2917', 'stage1', '해외 직구', 18)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_449', 'stage1', '공동구매', 19)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_897', 'stage1', '대중명품', 20)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2805', 'stage1', '포미족', 21)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2835', 'stage1', '프레이밍 효과', 22)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_813', 'stage1', '노쇼', 23)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1126', 'stage1', '밀레니얼 세대', 24)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_953', 'stage1', '디지털 네이티브', 25)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1009', 'stage1', '리터루족', 26)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2565', 'stage1', '치킨 게임', 27)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_3011', 'stage1', '회색 코뿔소', 28)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2434', 'stage1', '지정학적 리스크', 29)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2777', 'stage1', '팬데믹', 30)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.stages (stage_id, name_ko, display_order, is_optional)
values ('stage2', '금융과 투자', 2, false)
on conflict (stage_id) do update set
  name_ko = excluded.name_ko,
  display_order = excluded.display_order,
  is_optional = excluded.is_optional;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1237', 'stage2', '복리이자', 1)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_859', 'stage2', '단리이자', 2)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1875', 'stage2', '예대마진', 3)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_290', 'stage2', '가산금리', 4)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1874', 'stage2', '예금자보호', 5)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2363', 'stage2', '주택청약종합저축', 6)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1852', 'stage2', '연금저축', 7)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1320', 'stage2', '비과세저축', 8)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_331', 'stage2', '개인신용평가시스템', 9)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_313', 'stage2', '간편결제서비스', 10)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_430', 'stage2', '고정 금리 저당 대출', 11)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1213', 'stage2', '변동 금리 저당 대출', 12)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1023', 'stage2', '마이너스 대출', 13)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_911', 'stage2', '대환대출', 14)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2358', 'stage2', '주택담보인정비율', 15)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2519', 'stage2', '총부채원리금상환비율', 16)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_668', 'stage2', '금리인하 요구권', 17)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_885', 'stage2', '대부업', 18)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2293', 'stage2', '제2금융권', 19)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2844', 'stage2', '프리워크아웃', 20)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_333', 'stage2', '개인워크아웃', 21)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1510', 'stage2', '소비자 파산', 22)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2605', 'stage2', '코스트에버리지', 23)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2603', 'stage2', '코스닥', 24)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2606', 'stage2', '코스피200', 25)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1634', 'stage2', '시가총액', 26)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_84', 'stage2', 'ELS', 27)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1992', 'stage2', '유가증권', 28)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_459', 'stage2', '공모펀드', 29)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1410', 'stage2', '상장지수펀드', 30)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2078', 'stage2', '인덱스펀드', 31)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_234', 'stage2', 'Short Sale', 32)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_457', 'stage2', '공모주청약', 33)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_75', 'stage2', 'DB형 퇴직연금', 34)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_571', 'stage2', '국민연금 소득대체율', 35)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_76', 'stage2', 'DC형 퇴직연금', 36)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1226', 'stage2', '보장성보험', 37)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1754', 'stage2', '암호화폐', 38)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1285', 'stage2', '분할상환식 담보대출', 39)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1227', 'stage2', '보증보험', 40)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.stages (stage_id, name_ko, display_order, is_optional)
values ('stage3', '거시경제와 통화·재정정책', 3, false)
on conflict (stage_id) do update set
  name_ko = excluded.name_ko,
  display_order = excluded.display_order,
  is_optional = excluded.is_optional;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_745', 'stage3', '기회비용', 1)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1034', 'stage3', '매몰비용', 2)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2883', 'stage3', '한계효용체감의 법칙', 3)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2881', 'stage3', '한계비용', 4)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1225', 'stage3', '보이지 않는 손', 5)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1642', 'stage3', '시장실패', 6)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2284', 'stage3', '정부실패', 7)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1932', 'stage3', '외부효과', 8)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_445', 'stage3', '공공재', 9)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_928', 'stage3', '독점', 10)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_500', 'stage3', '과점시장', 11)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_610', 'stage3', '규모의 경제', 12)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_918', 'stage3', '도덕적 해이', 13)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1836', 'stage3', '역선택', 14)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_566', 'stage3', '국내총생산/국민총생산', 15)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1708', 'stage3', '실질 GDP', 16)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_578', 'stage3', '국민총소득', 17)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_3', 'stage3', '1인당 국민소득', 18)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_391', 'stage3', '경제성장률', 19)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2162', 'stage3', '잠재성장률', 20)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_369', 'stage3', '경기순환', 21)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_368', 'stage3', '경기선행지수', 22)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2091', 'stage3', '인플레이션', 23)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_960', 'stage3', '디플레이션', 24)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1610', 'stage3', '스태그플레이션', 25)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1514', 'stage3', '소비자물가지수·생활물가지수', 26)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1703', 'stage3', '실업률', 27)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_422', 'stage3', '고용률', 28)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_401', 'stage3', '경제활동인구', 29)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_735', 'stage3', '기준금리', 30)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2701', 'stage3', '통화정책', 31)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1784', 'stage3', '양적완화', 32)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_750', 'stage3', '긴축정책', 33)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2694', 'stage3', '통화량', 34)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2382', 'stage3', '중앙은행', 35)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1879', 'stage3', '예산', 36)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2543', 'stage3', '추가경정예산', 37)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2200', 'stage3', '재정적자', 38)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_554', 'stage3', '국가채무', 39)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1501', 'stage3', '소득세', 40)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1246', 'stage3', '부가가치세', 41)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2446', 'stage3', '직접세', 42)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_311', 'stage3', '간접세', 43)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_837', 'stage3', '누진세율', 44)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1973', 'stage3', '원천징수', 45)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1499', 'stage3', '소득공제', 46)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1856', 'stage3', '연말정산', 47)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2401', 'stage3', '지니계수', 48)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1372', 'stage3', '사회보험', 49)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2076', 'stage3', '인구절벽', 50)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.stages (stage_id, name_ko, display_order, is_optional)
values ('stage4', '국제경제와 산업·기술동향', 4, false)
on conflict (stage_id) do update set
  name_ko = excluded.name_ko,
  display_order = excluded.display_order,
  is_optional = excluded.is_optional;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1323', 'stage4', '비교우위', 1)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2267', 'stage4', '절대우위', 2)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_507', 'stage4', '관세', 3)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1321', 'stage4', '비관세장벽', 4)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1560', 'stage4', '수입쿼터', 5)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1234', 'stage4', '보호무역주의', 6)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_913', 'stage4', '덤핑', 7)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_104', 'stage4', 'FTA', 8)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1472', 'stage4', '세계무역기구', 9)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2542', 'stage4', '최혜국대우', 10)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1969', 'stage4', '원산지규정', 11)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_590', 'stage4', '국제수지', 12)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1085', 'stage4', '무역의존도', 13)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_519', 'stage4', '교역조건', 14)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2370', 'stage4', '중간재', 15)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_651', 'stage4', '근린궁핍화정책', 16)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_144', 'stage4', 'J커브 효과', 17)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1293', 'stage4', '불황형 흑자', 18)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2794', 'stage4', '평가절하/절상', 19)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1975', 'stage4', '원화절상', 20)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1976', 'stage4', '원화절하', 21)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2987', 'stage4', '환리스크', 22)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_3000', 'stage4', '환헤지', 23)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_742', 'stage4', '기축통화', 24)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1937', 'stage4', '외환보유액', 25)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2696', 'stage4', '통화스왑', 26)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_595', 'stage4', '국제통화기금', 27)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1475', 'stage4', '세계은행', 28)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_113', 'stage4', 'G20', 29)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_182', 'stage4', 'OECD', 30)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_997', 'stage4', '리먼사태', 31)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1064', 'stage4', '모라토리엄', 32)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1505', 'stage4', '소버린리스크', 33)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_11', 'stage4', '4차 산업혁명', 34)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_951', 'stage4', '디지털 경제', 35)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2847', 'stage4', '플랫폼 비즈니스', 36)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_531', 'stage4', '구독경제', 37)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1914', 'stage4', '온디맨드 경제', 38)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1310', 'stage4', '블록체인', 39)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_207', 'stage4', 'R&D', 40)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1664', 'stage4', '신생 기업', 41)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1208', 'stage4', '벤처캐피탈', 42)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2636', 'stage4', '크라우드펀딩', 43)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_846', 'stage4', '다국적기업', 44)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1001', 'stage4', '리쇼어링', 45)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_220', 'stage4', 'SCM', 46)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1925', 'stage4', '외국인 직접투자', 47)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2082', 'stage4', '인수합병', 48)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_718', 'stage4', '기업공개', 49)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2187', 'stage4', '재무제표', 50)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1869', 'stage4', '영업이익', 51)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1539', 'stage4', '손익분기점', 52)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_65', 'stage4', 'CSR', 53)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1164', 'stage4', '배출권거래제', 54)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1659', 'stage4', '신기후체제', 55)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2657', 'stage4', '탄소세', 56)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_484', 'stage4', '공정무역', 57)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2567', 'stage4', '카르텔', 58)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2433', 'stage4', '지적재산권', 59)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1444', 'stage4', '석유수출국기구', 60)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.stages (stage_id, name_ko, display_order, is_optional)
values ('stage5', 'TESAT·매경TEST 빈출 핵심 용어', 5, false)
on conflict (stage_id) do update set
  name_ko = excluded.name_ko,
  display_order = excluded.display_order,
  is_optional = excluded.is_optional;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1552', 'stage5', '수요의 법칙', 1)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1550', 'stage5', '수요의 가격탄력성', 2)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_617', 'stage5', '균형가격', 3)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1923', 'stage5', '완전경쟁시장', 4)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_928', 'stage5', '독점', 5)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_500', 'stage5', '과점시장', 6)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_929', 'stage5', '독점적 경쟁시장', 7)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2338', 'stage5', '죄수의 딜레마', 8)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1642', 'stage5', '시장실패', 9)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_745', 'stage5', '기회비용', 10)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2883', 'stage5', '한계효용체감의 법칙', 11)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1932', 'stage5', '외부효과', 12)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_445', 'stage5', '공공재', 13)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1836', 'stage5', '역선택', 14)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_918', 'stage5', '도덕적 해이', 15)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_566', 'stage5', '국내총생산/국민총생산', 16)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1514', 'stage5', '소비자물가지수·생활물가지수', 17)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2091', 'stage5', '인플레이션', 18)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1610', 'stage5', '스태그플레이션', 19)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_369', 'stage5', '경기순환', 20)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1703', 'stage5', '실업률', 21)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_540', 'stage5', '구조적 실업', 22)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2863', 'stage5', '필립스곡선', 23)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2162', 'stage5', '잠재성장률', 24)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_735', 'stage5', '기준금리', 25)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2701', 'stage5', '통화정책', 26)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1784', 'stage5', '양적완화', 27)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1998', 'stage5', '유동성 함정', 28)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1631', 'stage5', '승수효과', 29)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_546', 'stage5', '구축효과', 30)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2401', 'stage5', '지니계수', 31)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1323', 'stage5', '비교우위', 32)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1234', 'stage5', '보호무역주의', 33)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_104', 'stage5', 'FTA', 34)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_590', 'stage5', '국제수지', 35)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_377', 'stage5', '경상수지', 36)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1214', 'stage5', '변동환율제도', 37)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2794', 'stage5', '평가절하/절상', 38)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_144', 'stage5', 'J커브 효과', 39)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_519', 'stage5', '교역조건', 40)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_10', 'stage5', '4Ps', 41)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_233', 'stage5', 'SWOT분석', 42)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2919', 'stage5', '핵심역량', 43)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1312', 'stage5', '블루오션', 44)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1964', 'stage5', '원가우위', 45)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_610', 'stage5', '규모의 경제', 46)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2082', 'stage5', '인수합병', 47)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2187', 'stage5', '재무제표', 48)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_899', 'stage5', '대차대조표', 49)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1848', 'stage5', '연결재무제표', 50)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1869', 'stage5', '영업이익', 51)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1539', 'stage5', '손익분기점', 52)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_315', 'stage5', '감가상각', 53)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_82', 'stage5', 'EBITDA', 54)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_211', 'stage5', 'ROE/ROI', 55)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_177', 'stage5', 'Net Present Value', 56)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2349', 'stage5', '주인-대리인 문제', 57)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_729', 'stage5', '기업지배구조', 58)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2112', 'stage5', '임금피크제', 59)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1613', 'stage5', '스톡옵션', 60)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1440', 'stage5', '서킷브레이커', 61)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1410', 'stage5', '상장지수펀드', 62)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2859', 'stage5', '핀테크', 63)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2519', 'stage5', '총부채원리금상환비율', 64)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_11', 'stage5', '4차 산업혁명', 65)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1310', 'stage5', '블록체인', 66)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_531', 'stage5', '구독경제', 67)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2656', 'stage5', '탄소배출권거래제', 68)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_1001', 'stage5', '리쇼어링', 69)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

insert into public.concepts (concept_id, stage_id, term, display_order)
values ('sisa_2309', 'stage5', '젠트리피케이션', 70)
on conflict (concept_id, stage_id) do update set
  term = excluded.term,
  display_order = excluded.display_order;

commit;
